<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Confidence Intervals | Statistical Inference via Data Science</title>
  <meta name="description" content="An open-source and fully-reproducible electronic textbook for teaching statistical inference using tidyverse data science tools." />
  <meta name="generator" content="bookdown 0.11 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Confidence Intervals | Statistical Inference via Data Science" />
  <meta property="og:type" content="book" />
  <meta property="og:url" content="https://nulib.github.io/moderndive_book/" />
  <meta property="og:image" content="https://nulib.github.io/moderndive_book/images/logos/book_cover.png" />
  <meta property="og:description" content="An open-source and fully-reproducible electronic textbook for teaching statistical inference using tidyverse data science tools." />
  <meta name="github-repo" content="nulib/moderndive_book" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Confidence Intervals | Statistical Inference via Data Science" />
  
  <meta name="twitter:description" content="An open-source and fully-reproducible electronic textbook for teaching statistical inference using tidyverse data science tools." />
  <meta name="twitter:image" content="https://nulib.github.io/moderndive_book/images/logos/book_cover.png" />

<meta name="author" content="Chester Ismay, Albert Y. Kim, Arend M. Kuyper, Elizabeth Tipton, and Kaitlyn Fitzgerald" />


<meta name="date" content="2019-08-16" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  <link rel="apple-touch-icon-precomposed" sizes="152x152" href="images/logos/favicons/apple-touch-icon.png" />
  <link rel="shortcut icon" href="images/logos/favicons/favicon.ico" type="image/x-icon" />
<link rel="prev" href="6-sampling.html">
<link rel="next" href="8-inference-for-regression.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89938436-1', 'auto');
  ga('send', 'pageview');

</script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#sec:intro-for-students"><i class="fa fa-check"></i><b>1.1</b> Introduction for students</a><ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#subsec:learning-goals"><i class="fa fa-check"></i><b>1.1.1</b> What you will learn from this book</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#subsec:pipeline"><i class="fa fa-check"></i><b>1.1.2</b> Data/science pipeline</a></li>
<li class="chapter" data-level="1.1.3" data-path="index.html"><a href="index.html#subsec:reproducible"><i class="fa fa-check"></i><b>1.1.3</b> Reproducible research</a></li>
<li class="chapter" data-level="1.1.4" data-path="index.html"><a href="index.html#final-note-for-students"><i class="fa fa-check"></i><b>1.1.4</b> Final note for students</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#sec:intro-instructors"><i class="fa fa-check"></i><b>1.2</b> Introduction for instructors</a><ul>
<li class="chapter" data-level="1.2.1" data-path="index.html"><a href="index.html#who-is-this-book-for"><i class="fa fa-check"></i><b>1.2.1</b> Who is this book for?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#datacamp"><i class="fa fa-check"></i><b>1.3</b> DataCamp</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#sec:connect-contribute"><i class="fa fa-check"></i><b>1.4</b> Connect and contribute</a></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#sec:about-book"><i class="fa fa-check"></i><b>1.5</b> About this book</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#sec:about-authors"><i class="fa fa-check"></i><b>1.6</b> About the authors</a><ul>
<li class="chapter" data-level="1.6.1" data-path="index.html"><a href="index.html#colophon"><i class="fa fa-check"></i><b>1.6.1</b> Colophon</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="2-getting-started.html"><a href="2-getting-started.html"><i class="fa fa-check"></i><b>2</b> Getting Started with Data in R</a><ul>
<li class="chapter" data-level="2.1" data-path="2-getting-started.html"><a href="2-getting-started.html#r-rstudio"><i class="fa fa-check"></i><b>2.1</b> What are R and RStudio?</a><ul>
<li class="chapter" data-level="2.1.1" data-path="2-getting-started.html"><a href="2-getting-started.html#installing-r-and-rstudio"><i class="fa fa-check"></i><b>2.1.1</b> Installing R and RStudio</a></li>
<li class="chapter" data-level="2.1.2" data-path="2-getting-started.html"><a href="2-getting-started.html#using-r-via-rstudio"><i class="fa fa-check"></i><b>2.1.2</b> Using R via RStudio</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="2-getting-started.html"><a href="2-getting-started.html#code"><i class="fa fa-check"></i><b>2.2</b> How do I code in R?</a><ul>
<li class="chapter" data-level="2.2.1" data-path="2-getting-started.html"><a href="2-getting-started.html#programming-concepts"><i class="fa fa-check"></i><b>2.2.1</b> Basic programming concepts and terminology</a></li>
<li class="chapter" data-level="2.2.2" data-path="2-getting-started.html"><a href="2-getting-started.html#errors-warnings-and-messages"><i class="fa fa-check"></i><b>2.2.2</b> Errors, warnings, and messages</a></li>
<li class="chapter" data-level="2.2.3" data-path="2-getting-started.html"><a href="2-getting-started.html#tips-on-learning-to-code"><i class="fa fa-check"></i><b>2.2.3</b> Tips on learning to code</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="2-getting-started.html"><a href="2-getting-started.html#packages"><i class="fa fa-check"></i><b>2.3</b> What are R packages?</a><ul>
<li class="chapter" data-level="2.3.1" data-path="2-getting-started.html"><a href="2-getting-started.html#package-installation"><i class="fa fa-check"></i><b>2.3.1</b> Package installation</a></li>
<li class="chapter" data-level="2.3.2" data-path="2-getting-started.html"><a href="2-getting-started.html#package-loading"><i class="fa fa-check"></i><b>2.3.2</b> Package loading</a></li>
<li class="chapter" data-level="2.3.3" data-path="2-getting-started.html"><a href="2-getting-started.html#package-use"><i class="fa fa-check"></i><b>2.3.3</b> Package use</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="2-getting-started.html"><a href="2-getting-started.html#nycflights13"><i class="fa fa-check"></i><b>2.4</b> Explore your first dataset</a><ul>
<li class="chapter" data-level="2.4.1" data-path="2-getting-started.html"><a href="2-getting-started.html#nycflights13-package"><i class="fa fa-check"></i><b>2.4.1</b> <code>nycflights13</code> package</a></li>
<li class="chapter" data-level="2.4.2" data-path="2-getting-started.html"><a href="2-getting-started.html#flights-data-frame"><i class="fa fa-check"></i><b>2.4.2</b> <code>flights</code> data frame</a></li>
<li class="chapter" data-level="2.4.3" data-path="2-getting-started.html"><a href="2-getting-started.html#exploredataframes"><i class="fa fa-check"></i><b>2.4.3</b> Exploring data frames</a></li>
<li class="chapter" data-level="2.4.4" data-path="2-getting-started.html"><a href="2-getting-started.html#help-files"><i class="fa fa-check"></i><b>2.4.4</b> Help files</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="2-getting-started.html"><a href="2-getting-started.html#conclusion"><i class="fa fa-check"></i><b>2.5</b> Conclusion</a><ul>
<li class="chapter" data-level="2.5.1" data-path="2-getting-started.html"><a href="2-getting-started.html#additional-resources"><i class="fa fa-check"></i><b>2.5.1</b> Additional resources</a></li>
<li class="chapter" data-level="2.5.2" data-path="2-getting-started.html"><a href="2-getting-started.html#whats-to-come"><i class="fa fa-check"></i><b>2.5.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>I Data Science via the tidyverse</b></span><ul>
<li class="chapter" data-level="" data-path="2-getting-started.html"><a href="2-getting-started.html#needed-packages"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="2.6" data-path="2-getting-started.html"><a href="2-getting-started.html#grammarofgraphics"><i class="fa fa-check"></i><b>2.6</b> The Grammar of Graphics</a><ul>
<li class="chapter" data-level="2.6.1" data-path="2-getting-started.html"><a href="2-getting-started.html#components-of-the-grammar"><i class="fa fa-check"></i><b>2.6.1</b> Components of the Grammar</a></li>
<li class="chapter" data-level="2.6.2" data-path="2-getting-started.html"><a href="2-getting-started.html#gapminder"><i class="fa fa-check"></i><b>2.6.2</b> Gapminder data</a></li>
<li class="chapter" data-level="2.6.3" data-path="2-getting-started.html"><a href="2-getting-started.html#other-components"><i class="fa fa-check"></i><b>2.6.3</b> Other components</a></li>
<li class="chapter" data-level="2.6.4" data-path="2-getting-started.html"><a href="2-getting-started.html#ggplot2-package"><i class="fa fa-check"></i><b>2.6.4</b> ggplot2 package</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="2-getting-started.html"><a href="2-getting-started.html#FiveNG"><i class="fa fa-check"></i><b>2.7</b> Five Named Graphs - The 5NG</a></li>
<li class="chapter" data-level="2.8" data-path="2-getting-started.html"><a href="2-getting-started.html#scatterplots"><i class="fa fa-check"></i><b>2.8</b> 5NG#1: Scatterplots</a><ul>
<li class="chapter" data-level="2.8.1" data-path="2-getting-started.html"><a href="2-getting-started.html#geompoint"><i class="fa fa-check"></i><b>2.8.1</b> Scatterplots via geom_point</a></li>
<li class="chapter" data-level="2.8.2" data-path="2-getting-started.html"><a href="2-getting-started.html#overplotting"><i class="fa fa-check"></i><b>2.8.2</b> Over-plotting</a></li>
<li class="chapter" data-level="2.8.3" data-path="2-getting-started.html"><a href="2-getting-started.html#summary"><i class="fa fa-check"></i><b>2.8.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="2-getting-started.html"><a href="2-getting-started.html#linegraphs"><i class="fa fa-check"></i><b>2.9</b> 5NG#2: Linegraphs</a><ul>
<li class="chapter" data-level="2.9.1" data-path="2-getting-started.html"><a href="2-getting-started.html#geomline"><i class="fa fa-check"></i><b>2.9.1</b> Linegraphs via geom_line</a></li>
<li class="chapter" data-level="2.9.2" data-path="2-getting-started.html"><a href="2-getting-started.html#summary-1"><i class="fa fa-check"></i><b>2.9.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.10" data-path="2-getting-started.html"><a href="2-getting-started.html#histograms"><i class="fa fa-check"></i><b>2.10</b> 5NG#3: Histograms</a><ul>
<li class="chapter" data-level="2.10.1" data-path="2-getting-started.html"><a href="2-getting-started.html#geomhistogram"><i class="fa fa-check"></i><b>2.10.1</b> Histograms via geom_histogram</a></li>
<li class="chapter" data-level="2.10.2" data-path="2-getting-started.html"><a href="2-getting-started.html#adjustbins"><i class="fa fa-check"></i><b>2.10.2</b> Adjusting the bins</a></li>
<li class="chapter" data-level="2.10.3" data-path="2-getting-started.html"><a href="2-getting-started.html#summary-2"><i class="fa fa-check"></i><b>2.10.3</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="2-getting-started.html"><a href="2-getting-started.html#facets"><i class="fa fa-check"></i><b>2.11</b> Facets</a></li>
<li class="chapter" data-level="2.12" data-path="2-getting-started.html"><a href="2-getting-started.html#boxplots"><i class="fa fa-check"></i><b>2.12</b> 5NG#4: Boxplots</a><ul>
<li class="chapter" data-level="2.12.1" data-path="2-getting-started.html"><a href="2-getting-started.html#geomboxplot"><i class="fa fa-check"></i><b>2.12.1</b> Boxplots via geom_boxplot</a></li>
<li class="chapter" data-level="2.12.2" data-path="2-getting-started.html"><a href="2-getting-started.html#summary-3"><i class="fa fa-check"></i><b>2.12.2</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.13" data-path="2-getting-started.html"><a href="2-getting-started.html#geombar"><i class="fa fa-check"></i><b>2.13</b> 5NG#5: Barplots</a><ul>
<li class="chapter" data-level="2.13.1" data-path="2-getting-started.html"><a href="2-getting-started.html#barplots-via-geom_bar-or-geom_col"><i class="fa fa-check"></i><b>2.13.1</b> Barplots via geom_bar or geom_col</a></li>
<li class="chapter" data-level="2.13.2" data-path="2-getting-started.html"><a href="2-getting-started.html#must-avoid-pie-charts"><i class="fa fa-check"></i><b>2.13.2</b> Must avoid pie charts!</a></li>
<li class="chapter" data-level="2.13.3" data-path="2-getting-started.html"><a href="2-getting-started.html#two-categ-barplot"><i class="fa fa-check"></i><b>2.13.3</b> Two categorical variables</a></li>
<li class="chapter" data-level="2.13.4" data-path="2-getting-started.html"><a href="2-getting-started.html#summary-4"><i class="fa fa-check"></i><b>2.13.4</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="2.14" data-path="2-getting-started.html"><a href="2-getting-started.html#conclusion-1"><i class="fa fa-check"></i><b>2.14</b> Conclusion</a><ul>
<li class="chapter" data-level="2.14.1" data-path="2-getting-started.html"><a href="2-getting-started.html#summary-table"><i class="fa fa-check"></i><b>2.14.1</b> Summary table</a></li>
<li class="chapter" data-level="2.14.2" data-path="2-getting-started.html"><a href="2-getting-started.html#argument-specification"><i class="fa fa-check"></i><b>2.14.2</b> Argument specification</a></li>
<li class="chapter" data-level="2.14.3" data-path="2-getting-started.html"><a href="2-getting-started.html#additional-resources-1"><i class="fa fa-check"></i><b>2.14.3</b> Additional resources</a></li>
<li class="chapter" data-level="2.14.4" data-path="2-getting-started.html"><a href="2-getting-started.html#whats-to-come-3"><i class="fa fa-check"></i><b>2.14.4</b> What’s to come</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="3-wrangling.html"><a href="3-wrangling.html"><i class="fa fa-check"></i><b>3</b> Data Wrangling</a><ul>
<li class="chapter" data-level="" data-path="3-wrangling.html"><a href="3-wrangling.html#needed-packages-1"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="3.1" data-path="3-wrangling.html"><a href="3-wrangling.html#piping"><i class="fa fa-check"></i><b>3.1</b> The pipe operator: <code>%&gt;%</code></a></li>
<li class="chapter" data-level="3.2" data-path="3-wrangling.html"><a href="3-wrangling.html#filter"><i class="fa fa-check"></i><b>3.2</b> <code>filter</code> rows</a></li>
<li class="chapter" data-level="3.3" data-path="3-wrangling.html"><a href="3-wrangling.html#summarize"><i class="fa fa-check"></i><b>3.3</b> <code>summarize</code> variables</a></li>
<li class="chapter" data-level="3.4" data-path="3-wrangling.html"><a href="3-wrangling.html#groupby"><i class="fa fa-check"></i><b>3.4</b> <code>group_by</code> rows</a><ul>
<li class="chapter" data-level="3.4.1" data-path="3-wrangling.html"><a href="3-wrangling.html#grouping-by-more-than-one-variable"><i class="fa fa-check"></i><b>3.4.1</b> Grouping by more than one variable</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="3-wrangling.html"><a href="3-wrangling.html#mutate"><i class="fa fa-check"></i><b>3.5</b> <code>mutate</code> existing variables</a></li>
<li class="chapter" data-level="3.6" data-path="3-wrangling.html"><a href="3-wrangling.html#arrange"><i class="fa fa-check"></i><b>3.6</b> <code>arrange</code> and sort rows</a></li>
<li class="chapter" data-level="3.7" data-path="3-wrangling.html"><a href="3-wrangling.html#joins"><i class="fa fa-check"></i><b>3.7</b> <code>join</code> data frames</a><ul>
<li class="chapter" data-level="3.7.1" data-path="3-wrangling.html"><a href="3-wrangling.html#matching-key-variable-names"><i class="fa fa-check"></i><b>3.7.1</b> Matching “key” variable names</a></li>
<li class="chapter" data-level="3.7.2" data-path="3-wrangling.html"><a href="3-wrangling.html#diff-key"><i class="fa fa-check"></i><b>3.7.2</b> Different “key” variable names</a></li>
<li class="chapter" data-level="3.7.3" data-path="3-wrangling.html"><a href="3-wrangling.html#multiple-key-variables"><i class="fa fa-check"></i><b>3.7.3</b> Multiple “key” variables</a></li>
<li class="chapter" data-level="3.7.4" data-path="3-wrangling.html"><a href="3-wrangling.html#normal-forms"><i class="fa fa-check"></i><b>3.7.4</b> Normal forms</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="3-wrangling.html"><a href="3-wrangling.html#other-verbs"><i class="fa fa-check"></i><b>3.8</b> Other verbs</a><ul>
<li class="chapter" data-level="3.8.1" data-path="3-wrangling.html"><a href="3-wrangling.html#select"><i class="fa fa-check"></i><b>3.8.1</b> <code>select</code> variables</a></li>
<li class="chapter" data-level="3.8.2" data-path="3-wrangling.html"><a href="3-wrangling.html#rename"><i class="fa fa-check"></i><b>3.8.2</b> <code>rename</code> variables</a></li>
<li class="chapter" data-level="3.8.3" data-path="3-wrangling.html"><a href="3-wrangling.html#top_n-values-of-a-variable"><i class="fa fa-check"></i><b>3.8.3</b> <code>top_n</code> values of a variable</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="3-wrangling.html"><a href="3-wrangling.html#conclusion-2"><i class="fa fa-check"></i><b>3.9</b> Conclusion</a><ul>
<li class="chapter" data-level="3.9.1" data-path="3-wrangling.html"><a href="3-wrangling.html#summary-table-1"><i class="fa fa-check"></i><b>3.9.1</b> Summary table</a></li>
<li class="chapter" data-level="3.9.2" data-path="3-wrangling.html"><a href="3-wrangling.html#additional-resources-2"><i class="fa fa-check"></i><b>3.9.2</b> Additional resources</a></li>
<li class="chapter" data-level="3.9.3" data-path="3-wrangling.html"><a href="3-wrangling.html#whats-to-come-1"><i class="fa fa-check"></i><b>3.9.3</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="4-tidy.html"><a href="4-tidy.html"><i class="fa fa-check"></i><b>4</b> Data Importing &amp; “Tidy” Data</a><ul>
<li class="chapter" data-level="" data-path="4-tidy.html"><a href="4-tidy.html#needed-packages-2"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="4.1" data-path="4-tidy.html"><a href="4-tidy.html#csv"><i class="fa fa-check"></i><b>4.1</b> Importing data</a><ul>
<li class="chapter" data-level="4.1.1" data-path="4-tidy.html"><a href="4-tidy.html#using-the-console"><i class="fa fa-check"></i><b>4.1.1</b> Using the console</a></li>
<li class="chapter" data-level="4.1.2" data-path="4-tidy.html"><a href="4-tidy.html#using-rstudios-interface"><i class="fa fa-check"></i><b>4.1.2</b> Using RStudio’s interface</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="4-tidy.html"><a href="4-tidy.html#tidy-data-ex"><i class="fa fa-check"></i><b>4.2</b> Tidy data</a><ul>
<li class="chapter" data-level="4.2.1" data-path="4-tidy.html"><a href="4-tidy.html#definition-of-tidy-data"><i class="fa fa-check"></i><b>4.2.1</b> Definition of “tidy” data</a></li>
<li class="chapter" data-level="4.2.2" data-path="4-tidy.html"><a href="4-tidy.html#converting-to-tidy-data"><i class="fa fa-check"></i><b>4.2.2</b> Converting to “tidy” data</a></li>
<li class="chapter" data-level="4.2.3" data-path="4-tidy.html"><a href="4-tidy.html#nycflights13-package-1"><i class="fa fa-check"></i><b>4.2.3</b> <code>nycflights13</code> package</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="4-tidy.html"><a href="4-tidy.html#case-study-tidy"><i class="fa fa-check"></i><b>4.3</b> Case study: Democracy in Guatemala</a></li>
<li class="chapter" data-level="4.4" data-path="4-tidy.html"><a href="4-tidy.html#conclusion-3"><i class="fa fa-check"></i><b>4.4</b> Conclusion</a><ul>
<li class="chapter" data-level="4.4.1" data-path="4-tidy.html"><a href="4-tidy.html#tidyverse-package"><i class="fa fa-check"></i><b>4.4.1</b> <code>tidyverse</code> package</a></li>
<li class="chapter" data-level="4.4.2" data-path="4-tidy.html"><a href="4-tidy.html#additional-resources-3"><i class="fa fa-check"></i><b>4.4.2</b> Additional resources</a></li>
<li class="chapter" data-level="4.4.3" data-path="4-tidy.html"><a href="4-tidy.html#whats-to-come-2"><i class="fa fa-check"></i><b>4.4.3</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Data Modeling via moderndive</b></span><ul>
<li class="chapter" data-level="" data-path="4-tidy.html"><a href="4-tidy.html#needed-packages-3"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="4.5" data-path="4-tidy.html"><a href="4-tidy.html#model1"><i class="fa fa-check"></i><b>4.5</b> One numerical explanatory variable</a><ul>
<li class="chapter" data-level="4.5.1" data-path="4-tidy.html"><a href="4-tidy.html#model1EDA"><i class="fa fa-check"></i><b>4.5.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="4.5.2" data-path="4-tidy.html"><a href="4-tidy.html#model1table"><i class="fa fa-check"></i><b>4.5.2</b> Simple linear regression</a></li>
<li class="chapter" data-level="4.5.3" data-path="4-tidy.html"><a href="4-tidy.html#model1points"><i class="fa fa-check"></i><b>4.5.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="4-tidy.html"><a href="4-tidy.html#model2"><i class="fa fa-check"></i><b>4.6</b> One categorical explanatory variable</a><ul>
<li class="chapter" data-level="4.6.1" data-path="4-tidy.html"><a href="4-tidy.html#model2EDA"><i class="fa fa-check"></i><b>4.6.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="4.6.2" data-path="4-tidy.html"><a href="4-tidy.html#model2table"><i class="fa fa-check"></i><b>4.6.2</b> Linear regression</a></li>
<li class="chapter" data-level="4.6.3" data-path="4-tidy.html"><a href="4-tidy.html#model2points"><i class="fa fa-check"></i><b>4.6.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="4-tidy.html"><a href="4-tidy.html#related-topics"><i class="fa fa-check"></i><b>4.7</b> Related topics</a><ul>
<li class="chapter" data-level="4.7.1" data-path="4-tidy.html"><a href="4-tidy.html#correlationcoefficient"><i class="fa fa-check"></i><b>4.7.1</b> Correlation coefficient</a></li>
<li class="chapter" data-level="4.7.2" data-path="4-tidy.html"><a href="4-tidy.html#correlation-is-not-causation"><i class="fa fa-check"></i><b>4.7.2</b> Correlation is not necessarily causation</a></li>
<li class="chapter" data-level="4.7.3" data-path="4-tidy.html"><a href="4-tidy.html#leastsquares"><i class="fa fa-check"></i><b>4.7.3</b> Best fitting line</a></li>
<li class="chapter" data-level="4.7.4" data-path="4-tidy.html"><a href="4-tidy.html#underthehood"><i class="fa fa-check"></i><b>4.7.4</b> <code>get_regression_x()</code> functions</a></li>
</ul></li>
<li class="chapter" data-level="4.8" data-path="4-tidy.html"><a href="4-tidy.html#conclusion-4"><i class="fa fa-check"></i><b>4.8</b> Conclusion</a><ul>
<li class="chapter" data-level="4.8.1" data-path="4-tidy.html"><a href="4-tidy.html#additional-resources-4"><i class="fa fa-check"></i><b>4.8.1</b> Additional resources</a></li>
<li class="chapter" data-level="4.8.2" data-path="2-getting-started.html"><a href="2-getting-started.html#whats-to-come-3"><i class="fa fa-check"></i><b>4.8.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html"><i class="fa fa-check"></i><b>5</b> Multiple Regression</a><ul>
<li class="chapter" data-level="" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#needed-packages-4"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="5.1" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#model3"><i class="fa fa-check"></i><b>5.1</b> Two numerical explanatory variables</a><ul>
<li class="chapter" data-level="5.1.1" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#model3EDA"><i class="fa fa-check"></i><b>5.1.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="5.1.2" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#model3table"><i class="fa fa-check"></i><b>5.1.2</b> Multiple regression</a></li>
<li class="chapter" data-level="5.1.3" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#model3points"><i class="fa fa-check"></i><b>5.1.3</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#model4"><i class="fa fa-check"></i><b>5.2</b> One numerical &amp; one categorical explanatory variable</a><ul>
<li class="chapter" data-level="5.2.1" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#model4EDA"><i class="fa fa-check"></i><b>5.2.1</b> Exploratory data analysis</a></li>
<li class="chapter" data-level="5.2.2" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#model4table"><i class="fa fa-check"></i><b>5.2.2</b> Multiple regression: Parallel slopes model</a></li>
<li class="chapter" data-level="5.2.3" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#model4interactiontable"><i class="fa fa-check"></i><b>5.2.3</b> Multiple regression: Interaction model</a></li>
<li class="chapter" data-level="5.2.4" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#model4points"><i class="fa fa-check"></i><b>5.2.4</b> Observed/fitted values and residuals</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#related-topics-1"><i class="fa fa-check"></i><b>5.3</b> Related topics</a><ul>
<li class="chapter" data-level="5.3.1" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#correlationcoefficient2"><i class="fa fa-check"></i><b>5.3.1</b> More on the correlation coefficient</a></li>
<li class="chapter" data-level="5.3.2" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#simpsonsparadox"><i class="fa fa-check"></i><b>5.3.2</b> Simpson’s Paradox</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#conclusion-5"><i class="fa fa-check"></i><b>5.4</b> Conclusion</a><ul>
<li class="chapter" data-level="5.4.1" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#additional-resources-5"><i class="fa fa-check"></i><b>5.4.1</b> Additional resources</a></li>
<li class="chapter" data-level="5.4.2" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#whats-to-come-4"><i class="fa fa-check"></i><b>5.4.2</b> What’s to come?</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>III Inference via infer</b></span><ul>
<li class="chapter" data-level="5.5" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#terminology"><i class="fa fa-check"></i><b>5.5</b> Terminology &amp; Notation</a></li>
<li class="chapter" data-level="5.6" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#sample_selection"><i class="fa fa-check"></i><b>5.6</b> Populations &amp; Sampling</a></li>
<li class="chapter" data-level="5.7" data-path="5-multiple-regression.html"><a href="5-multiple-regression.html#samples"><i class="fa fa-check"></i><b>5.7</b> Samples &amp; Populations</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="6-sampling.html"><a href="6-sampling.html"><i class="fa fa-check"></i><b>6</b> Sampling Distributions</a><ul>
<li class="chapter" data-level="" data-path="6-sampling.html"><a href="6-sampling.html#needed-packages-5"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="6.1" data-path="6-sampling.html"><a href="6-sampling.html#theory"><i class="fa fa-check"></i><b>6.1</b> Theory of Repeated Samples</a></li>
<li class="chapter" data-level="6.2" data-path="6-sampling.html"><a href="6-sampling.html#sampling-activity"><i class="fa fa-check"></i><b>6.2</b> Sampling Activity</a><ul>
<li class="chapter" data-level="6.2.1" data-path="6-sampling.html"><a href="6-sampling.html#what-proportion-of-this-bowls-balls-are-red"><i class="fa fa-check"></i><b>6.2.1</b> What proportion of this bowl’s balls are red?</a></li>
<li class="chapter" data-level="6.2.2" data-path="6-sampling.html"><a href="6-sampling.html#using-the-shovel-once"><i class="fa fa-check"></i><b>6.2.2</b> Using the shovel once</a></li>
<li class="chapter" data-level="6.2.3" data-path="6-sampling.html"><a href="6-sampling.html#student-shovels"><i class="fa fa-check"></i><b>6.2.3</b> Using the shovel 33 times</a></li>
<li class="chapter" data-level="6.2.4" data-path="6-sampling.html"><a href="6-sampling.html#what-are-we-doing-here"><i class="fa fa-check"></i><b>6.2.4</b> What are we doing here?</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="6-sampling.html"><a href="6-sampling.html#sampling-simulation"><i class="fa fa-check"></i><b>6.3</b> Computer simulation</a><ul>
<li class="chapter" data-level="6.3.1" data-path="6-sampling.html"><a href="6-sampling.html#using-the-virtual-shovel-once"><i class="fa fa-check"></i><b>6.3.1</b> Using the virtual shovel once</a></li>
<li class="chapter" data-level="6.3.2" data-path="6-sampling.html"><a href="6-sampling.html#using-the-virtual-shovel-33-times"><i class="fa fa-check"></i><b>6.3.2</b> Using the virtual shovel 33 times</a></li>
<li class="chapter" data-level="6.3.3" data-path="6-sampling.html"><a href="6-sampling.html#using-the-virtual-shovel-1000-times"><i class="fa fa-check"></i><b>6.3.3</b> Using the virtual shovel 1000 times</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="6-sampling.html"><a href="6-sampling.html#properties_s"><i class="fa fa-check"></i><b>6.4</b> Properties of Sampling Distributions</a><ul>
<li class="chapter" data-level="6.4.1" data-path="6-sampling.html"><a href="6-sampling.html#dist"><i class="fa fa-check"></i><b>6.4.1</b> Distribution</a></li>
<li class="chapter" data-level="6.4.2" data-path="6-sampling.html"><a href="6-sampling.html#bias"><i class="fa fa-check"></i><b>6.4.2</b> Mean of the sampling distribution</a></li>
<li class="chapter" data-level="6.4.3" data-path="6-sampling.html"><a href="6-sampling.html#precision"><i class="fa fa-check"></i><b>6.4.3</b> Standard deviation of the sampling distribution</a></li>
<li class="chapter" data-level="6.4.4" data-path="6-sampling.html"><a href="6-sampling.html#conf"><i class="fa fa-check"></i><b>6.4.4</b> Confusing concepts</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="6-sampling.html"><a href="6-sampling.html#size"><i class="fa fa-check"></i><b>6.5</b> Sample Size and Sampling Distributions</a><ul>
<li class="chapter" data-level="6.5.1" data-path="6-sampling.html"><a href="6-sampling.html#eg1"><i class="fa fa-check"></i><b>6.5.1</b> Sampling balls with different sized shovels</a></li>
</ul></li>
<li class="chapter" data-level="6.6" data-path="6-sampling.html"><a href="6-sampling.html#clt"><i class="fa fa-check"></i><b>6.6</b> Central Limit Theorem (CLT)</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="7-CIs.html"><a href="7-CIs.html"><i class="fa fa-check"></i><b>7</b> Confidence Intervals</a><ul>
<li class="chapter" data-level="7.1" data-path="7-CIs.html"><a href="7-CIs.html#needed-packages-6"><i class="fa fa-check"></i><b>7.1</b> Needed Packages</a><ul>
<li class="chapter" data-level="7.1.1" data-path="6-sampling.html"><a href="6-sampling.html#theory"><i class="fa fa-check"></i><b>7.1.1</b> Theory based upon assumptions and models</a></li>
<li class="chapter" data-level="7.1.2" data-path="7-CIs.html"><a href="7-CIs.html#bootstrap"><i class="fa fa-check"></i><b>7.1.2</b> 10.2 Bootstrap</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="7-CIs.html"><a href="7-CIs.html#resampling-tactile"><i class="fa fa-check"></i><b>7.2</b> Pennies activity</a><ul>
<li class="chapter" data-level="7.2.1" data-path="7-CIs.html"><a href="7-CIs.html#what-is-the-average-year-on-us-pennies-in-2019"><i class="fa fa-check"></i><b>7.2.1</b> What is the average year on US pennies in 2019?</a></li>
<li class="chapter" data-level="7.2.2" data-path="7-CIs.html"><a href="7-CIs.html#resampling-once"><i class="fa fa-check"></i><b>7.2.2</b> Resampling once</a></li>
<li class="chapter" data-level="7.2.3" data-path="7-CIs.html"><a href="7-CIs.html#student-resamples"><i class="fa fa-check"></i><b>7.2.3</b> Resampling 35 times</a></li>
<li class="chapter" data-level="7.2.4" data-path="7-CIs.html"><a href="7-CIs.html#what-did-we-just-do"><i class="fa fa-check"></i><b>7.2.4</b> What did we just do?</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="7-CIs.html"><a href="7-CIs.html#resampling-simulation"><i class="fa fa-check"></i><b>7.3</b> Computer simulation of resampling</a><ul>
<li class="chapter" data-level="7.3.1" data-path="7-CIs.html"><a href="7-CIs.html#virtually-resampling-once"><i class="fa fa-check"></i><b>7.3.1</b> Virtually resampling once</a></li>
<li class="chapter" data-level="7.3.2" data-path="7-CIs.html"><a href="7-CIs.html#virtually-resampling-35-times"><i class="fa fa-check"></i><b>7.3.2</b> Virtually resampling 35 times</a></li>
<li class="chapter" data-level="7.3.3" data-path="7-CIs.html"><a href="7-CIs.html#bootstrap-1000-replicates"><i class="fa fa-check"></i><b>7.3.3</b> Virtually resampling 1000 times</a></li>
<li class="chapter" data-level="7.3.4" data-path="7-CIs.html"><a href="7-CIs.html#combining-an-estimate-with-its-precision"><i class="fa fa-check"></i><b>7.3.4</b> 10.3 Combining an estimate with its precision</a></li>
<li class="chapter" data-level="7.3.5" data-path="7-CIs.html"><a href="7-CIs.html#ci-with-the-normal-distribution"><i class="fa fa-check"></i><b>7.3.5</b> 10.4 CI with the Normal distribution</a></li>
<li class="chapter" data-level="7.3.6" data-path="7-CIs.html"><a href="7-CIs.html#ci-via-bootstrap"><i class="fa fa-check"></i><b>7.3.6</b> 10.5 CI via Bootstrap</a></li>
<li class="chapter" data-level="7.3.7" data-path="7-CIs.html"><a href="7-CIs.html#interpreting-a-confidence-interval"><i class="fa fa-check"></i><b>7.3.7</b> 10.6 Interpreting a Confidence Interval</a></li>
<li class="chapter" data-level="7.3.8" data-path="7-CIs.html"><a href="7-CIs.html#examples-from-end-of-current-chapter-9"><i class="fa fa-check"></i><b>7.3.8</b> 10.7 Examples (from end of current chapter 9)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html"><i class="fa fa-check"></i><b>8</b> Inference for Regression</a><ul>
<li class="chapter" data-level="" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#needed-packages-7"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="8.1" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#simulation-based-inference-for-regression"><i class="fa fa-check"></i><b>8.1</b> Simulation-based Inference for Regression</a><ul>
<li class="chapter" data-level="8.1.1" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#data"><i class="fa fa-check"></i><b>8.1.1</b> Data</a></li>
<li class="chapter" data-level="8.1.2" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#test-statistic-delta"><i class="fa fa-check"></i><b>8.1.2</b> Test statistic <span class="math inline">\(\delta\)</span></a></li>
<li class="chapter" data-level="8.1.3" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#observed-effect-delta"><i class="fa fa-check"></i><b>8.1.3</b> Observed effect <span class="math inline">\(\delta^*\)</span></a></li>
<li class="chapter" data-level="8.1.4" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#model-of-h_0"><i class="fa fa-check"></i><b>8.1.4</b> Model of <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="8.1.5" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#simulated-data"><i class="fa fa-check"></i><b>8.1.5</b> Simulated data</a></li>
<li class="chapter" data-level="8.1.6" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#distribution-of-delta-under-h_0"><i class="fa fa-check"></i><b>8.1.6</b> Distribution of <span class="math inline">\(\delta\)</span> under <span class="math inline">\(H_0\)</span></a></li>
<li class="chapter" data-level="8.1.7" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#the-p-value"><i class="fa fa-check"></i><b>8.1.7</b> The p-value</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#bootstrapping-for-the-regression-slope"><i class="fa fa-check"></i><b>8.2</b> Bootstrapping for the regression slope</a></li>
<li class="chapter" data-level="8.3" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#inference-for-multiple-regression"><i class="fa fa-check"></i><b>8.3</b> Inference for multiple regression</a><ul>
<li class="chapter" data-level="8.3.1" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#refresher-professor-evaluations-data"><i class="fa fa-check"></i><b>8.3.1</b> Refresher: Professor evaluations data</a></li>
<li class="chapter" data-level="8.3.2" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#refresher-visualizations"><i class="fa fa-check"></i><b>8.3.2</b> Refresher: Visualizations</a></li>
<li class="chapter" data-level="8.3.3" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#refresher-regression-tables"><i class="fa fa-check"></i><b>8.3.3</b> Refresher: Regression tables</a></li>
<li class="chapter" data-level="8.3.4" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#script-of-r-code"><i class="fa fa-check"></i><b>8.3.4</b> Script of R code</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#residual-analysis"><i class="fa fa-check"></i><b>8.4</b> Residual analysis</a><ul>
<li class="chapter" data-level="8.4.1" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#model1residuals"><i class="fa fa-check"></i><b>8.4.1</b> Residual analysis</a></li>
<li class="chapter" data-level="8.4.2" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#model2residuals"><i class="fa fa-check"></i><b>8.4.2</b> Residual analysis</a></li>
<li class="chapter" data-level="8.4.3" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#model3residuals"><i class="fa fa-check"></i><b>8.4.3</b> Residual analysis</a></li>
<li class="chapter" data-level="8.4.4" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#model4residuals"><i class="fa fa-check"></i><b>8.4.4</b> Residual analysis</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>IV Conclusion</b></span><ul>
<li class="chapter" data-level="" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#needed-packages-8"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="8.5" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#seattle-house-prices"><i class="fa fa-check"></i><b>8.5</b> Case study: Seattle house prices</a><ul>
<li class="chapter" data-level="8.5.1" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#house-prices-EDA-I"><i class="fa fa-check"></i><b>8.5.1</b> Exploratory data analysis (EDA)</a></li>
<li class="chapter" data-level="8.5.2" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#log10-transformations"><i class="fa fa-check"></i><b>8.5.2</b> log10 transformations</a></li>
<li class="chapter" data-level="8.5.3" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#eda-part-ii"><i class="fa fa-check"></i><b>8.5.3</b> EDA Part II</a></li>
<li class="chapter" data-level="8.5.4" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#house-prices-regression"><i class="fa fa-check"></i><b>8.5.4</b> Regression modeling</a></li>
<li class="chapter" data-level="8.5.5" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#house-prices-inference-for-regression"><i class="fa fa-check"></i><b>8.5.5</b> Inference for regression</a></li>
<li class="chapter" data-level="8.5.6" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#house-prices-making-predictions"><i class="fa fa-check"></i><b>8.5.6</b> Making predictions</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#data-journalism"><i class="fa fa-check"></i><b>8.6</b> Case study: Effective data storytelling</a><ul>
<li class="chapter" data-level="8.6.1" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#bechdel-test-for-hollywood-gender-representation"><i class="fa fa-check"></i><b>8.6.1</b> Bechdel test for Hollywood gender representation</a></li>
<li class="chapter" data-level="8.6.2" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#us-births-in-1999"><i class="fa fa-check"></i><b>8.6.2</b> US Births in 1999</a></li>
<li class="chapter" data-level="8.6.3" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#other-examples"><i class="fa fa-check"></i><b>8.6.3</b> Other examples</a></li>
<li class="chapter" data-level="8.6.4" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#script-of-r-code-1"><i class="fa fa-check"></i><b>8.6.4</b> Script of R code</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="8-inference-for-regression.html"><a href="8-inference-for-regression.html#concluding-remarks"><i class="fa fa-check"></i>Concluding remarks</a></li>
</ul></li>
<li class="appendix"><span><b>Appendix</b></span></li>
<li class="chapter" data-level="A" data-path="A-appendixA.html"><a href="A-appendixA.html"><i class="fa fa-check"></i><b>A</b> Statistical Background</a><ul>
<li class="chapter" data-level="A.1" data-path="A-appendixA.html"><a href="A-appendixA.html#basic-statistical-terms"><i class="fa fa-check"></i><b>A.1</b> Basic statistical terms</a><ul>
<li class="chapter" data-level="A.1.1" data-path="A-appendixA.html"><a href="A-appendixA.html#mean"><i class="fa fa-check"></i><b>A.1.1</b> Mean</a></li>
<li class="chapter" data-level="A.1.2" data-path="A-appendixA.html"><a href="A-appendixA.html#median"><i class="fa fa-check"></i><b>A.1.2</b> Median</a></li>
<li class="chapter" data-level="A.1.3" data-path="A-appendixA.html"><a href="A-appendixA.html#standard-deviation"><i class="fa fa-check"></i><b>A.1.3</b> Standard deviation</a></li>
<li class="chapter" data-level="A.1.4" data-path="A-appendixA.html"><a href="A-appendixA.html#five-number-summary"><i class="fa fa-check"></i><b>A.1.4</b> Five-number summary</a></li>
<li class="chapter" data-level="A.1.5" data-path="A-appendixA.html"><a href="A-appendixA.html#distribution"><i class="fa fa-check"></i><b>A.1.5</b> Distribution</a></li>
<li class="chapter" data-level="A.1.6" data-path="A-appendixA.html"><a href="A-appendixA.html#outliers"><i class="fa fa-check"></i><b>A.1.6</b> Outliers</a></li>
</ul></li>
<li class="chapter" data-level="A.2" data-path="A-appendixA.html"><a href="A-appendixA.html#normal-distribution-discussion"><i class="fa fa-check"></i><b>A.2</b> Normal distribution discussion</a></li>
</ul></li>
<li class="chapter" data-level="B" data-path="B-appendixB.html"><a href="B-appendixB.html"><i class="fa fa-check"></i><b>B</b> Inference Examples</a><ul>
<li class="chapter" data-level="" data-path="B-appendixB.html"><a href="B-appendixB.html#needed-packages-9"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="B.1" data-path="B-appendixB.html"><a href="B-appendixB.html#inference-mind-map"><i class="fa fa-check"></i><b>B.1</b> Inference mind map</a></li>
<li class="chapter" data-level="B.2" data-path="B-appendixB.html"><a href="B-appendixB.html#one-mean"><i class="fa fa-check"></i><b>B.2</b> One mean</a><ul>
<li class="chapter" data-level="B.2.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement"><i class="fa fa-check"></i><b>B.2.1</b> Problem statement</a></li>
<li class="chapter" data-level="B.2.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses"><i class="fa fa-check"></i><b>B.2.2</b> Competing hypotheses</a></li>
<li class="chapter" data-level="B.2.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data"><i class="fa fa-check"></i><b>B.2.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.2.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods"><i class="fa fa-check"></i><b>B.2.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.2.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods"><i class="fa fa-check"></i><b>B.2.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.2.6" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results"><i class="fa fa-check"></i><b>B.2.6</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.3" data-path="B-appendixB.html"><a href="B-appendixB.html#one-proportion"><i class="fa fa-check"></i><b>B.3</b> One proportion</a><ul>
<li class="chapter" data-level="B.3.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement-1"><i class="fa fa-check"></i><b>B.3.1</b> Problem statement</a></li>
<li class="chapter" data-level="B.3.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-1"><i class="fa fa-check"></i><b>B.3.2</b> Competing hypotheses</a></li>
<li class="chapter" data-level="B.3.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-1"><i class="fa fa-check"></i><b>B.3.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.3.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-1"><i class="fa fa-check"></i><b>B.3.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.3.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-1"><i class="fa fa-check"></i><b>B.3.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.3.6" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-1"><i class="fa fa-check"></i><b>B.3.6</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.4" data-path="B-appendixB.html"><a href="B-appendixB.html#two-proportions"><i class="fa fa-check"></i><b>B.4</b> Two proportions</a><ul>
<li class="chapter" data-level="B.4.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement-2"><i class="fa fa-check"></i><b>B.4.1</b> Problem statement</a></li>
<li class="chapter" data-level="B.4.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-2"><i class="fa fa-check"></i><b>B.4.2</b> Competing hypotheses</a></li>
<li class="chapter" data-level="B.4.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-2"><i class="fa fa-check"></i><b>B.4.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.4.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-2"><i class="fa fa-check"></i><b>B.4.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.4.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-2"><i class="fa fa-check"></i><b>B.4.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.4.6" data-path="B-appendixB.html"><a href="B-appendixB.html#check-conditions-2"><i class="fa fa-check"></i><b>B.4.6</b> Check conditions</a></li>
<li class="chapter" data-level="B.4.7" data-path="B-appendixB.html"><a href="B-appendixB.html#test-statistic-2"><i class="fa fa-check"></i><b>B.4.7</b> Test statistic</a></li>
<li class="chapter" data-level="B.4.8" data-path="B-appendixB.html"><a href="B-appendixB.html#state-conclusion-2"><i class="fa fa-check"></i><b>B.4.8</b> State conclusion</a></li>
<li class="chapter" data-level="B.4.9" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-2"><i class="fa fa-check"></i><b>B.4.9</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.5" data-path="B-appendixB.html"><a href="B-appendixB.html#two-means-independent-samples"><i class="fa fa-check"></i><b>B.5</b> Two means (independent samples)</a><ul>
<li class="chapter" data-level="B.5.1" data-path="B-appendixB.html"><a href="B-appendixB.html#problem-statement-3"><i class="fa fa-check"></i><b>B.5.1</b> Problem statement</a></li>
<li class="chapter" data-level="B.5.2" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-3"><i class="fa fa-check"></i><b>B.5.2</b> Competing hypotheses</a></li>
<li class="chapter" data-level="B.5.3" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-3"><i class="fa fa-check"></i><b>B.5.3</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.5.4" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-3"><i class="fa fa-check"></i><b>B.5.4</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.5.5" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-3"><i class="fa fa-check"></i><b>B.5.5</b> Traditional methods</a></li>
<li class="chapter" data-level="B.5.6" data-path="B-appendixB.html"><a href="B-appendixB.html#test-statistic-3"><i class="fa fa-check"></i><b>B.5.6</b> Test statistic</a></li>
<li class="chapter" data-level="B.5.7" data-path="B-appendixB.html"><a href="B-appendixB.html#compute-p-value-1"><i class="fa fa-check"></i><b>B.5.7</b> Compute <span class="math inline">\(p\)</span>-value</a></li>
<li class="chapter" data-level="B.5.8" data-path="B-appendixB.html"><a href="B-appendixB.html#state-conclusion-3"><i class="fa fa-check"></i><b>B.5.8</b> State conclusion</a></li>
<li class="chapter" data-level="B.5.9" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-3"><i class="fa fa-check"></i><b>B.5.9</b> Comparing results</a></li>
</ul></li>
<li class="chapter" data-level="B.6" data-path="B-appendixB.html"><a href="B-appendixB.html#two-means-paired-samples"><i class="fa fa-check"></i><b>B.6</b> Two means (paired samples)</a><ul>
<li class="chapter" data-level="B.6.1" data-path="B-appendixB.html"><a href="B-appendixB.html#competing-hypotheses-4"><i class="fa fa-check"></i><b>B.6.1</b> Competing hypotheses</a></li>
<li class="chapter" data-level="B.6.2" data-path="B-appendixB.html"><a href="B-appendixB.html#exploring-the-sample-data-4"><i class="fa fa-check"></i><b>B.6.2</b> Exploring the sample data</a></li>
<li class="chapter" data-level="B.6.3" data-path="B-appendixB.html"><a href="B-appendixB.html#non-traditional-methods-4"><i class="fa fa-check"></i><b>B.6.3</b> Non-traditional methods</a></li>
<li class="chapter" data-level="B.6.4" data-path="B-appendixB.html"><a href="B-appendixB.html#traditional-methods-4"><i class="fa fa-check"></i><b>B.6.4</b> Traditional methods</a></li>
<li class="chapter" data-level="B.6.5" data-path="B-appendixB.html"><a href="B-appendixB.html#comparing-results-4"><i class="fa fa-check"></i><b>B.6.5</b> Comparing results</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="C" data-path="C-appendixC.html"><a href="C-appendixC.html"><i class="fa fa-check"></i><b>C</b> Reach for the Stars</a><ul>
<li class="chapter" data-level="" data-path="C-appendixC.html"><a href="C-appendixC.html#needed-packages-10"><i class="fa fa-check"></i>Needed packages</a></li>
<li class="chapter" data-level="C.1" data-path="C-appendixC.html"><a href="C-appendixC.html#sorted-barplots"><i class="fa fa-check"></i><b>C.1</b> Sorted barplots</a></li>
<li class="chapter" data-level="C.2" data-path="C-appendixC.html"><a href="C-appendixC.html#interactive-graphics"><i class="fa fa-check"></i><b>C.2</b> Interactive graphics</a><ul>
<li class="chapter" data-level="C.2.1" data-path="C-appendixC.html"><a href="C-appendixC.html#interactive-linegraphs"><i class="fa fa-check"></i><b>C.2.1</b> Interactive linegraphs</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="D" data-path="D-appendixD.html"><a href="D-appendixD.html"><i class="fa fa-check"></i><b>D</b> Learning Check Solutions</a><ul>
<li class="chapter" data-level="D.1" data-path="D-appendixD.html"><a href="D-appendixD.html#chapter-2-solutions"><i class="fa fa-check"></i><b>D.1</b> Chapter 2 Solutions</a></li>
<li class="chapter" data-level="D.2" data-path="D-appendixD.html"><a href="D-appendixD.html#chapter-3-solutions"><i class="fa fa-check"></i><b>D.2</b> Chapter 3 Solutions</a></li>
<li class="chapter" data-level="D.3" data-path="D-appendixD.html"><a href="D-appendixD.html#chapter-4-solutions"><i class="fa fa-check"></i><b>D.3</b> Chapter 4 Solutions</a></li>
<li class="chapter" data-level="D.4" data-path="D-appendixD.html"><a href="D-appendixD.html#chapter-5-solutions"><i class="fa fa-check"></i><b>D.4</b> Chapter 5 Solutions</a></li>
<li class="chapter" data-level="D.5" data-path="D-appendixD.html"><a href="D-appendixD.html#chapter-6-solutions"><i class="fa fa-check"></i><b>D.5</b> Chapter 6 Solutions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Statistical Inference via Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<html>
<img src='https://moderndive.com/wide_format.png' alt="ModernDive">
</html>
<div id="CIs" class="section level1">
<h1><span class="header-section-number">Chapter 7</span> Confidence Intervals</h1>
<p>In Chapter <a href="6-sampling.html#sampling">6</a>, we developed a theory of repeated samples. But what does this mean for your data analysis? If you only have one sample in front of you, how are you supposed to understand properties of the sampling distribution and your estimators? In this chapter we tackle these questions using two approaches: 1) based upon formulas provided to us via mathematical theory, and 2) based upon approximations available computationally (bootstrap).</p>
<div id="needed-packages-6" class="section level2">
<h2><span class="header-section-number">7.1</span> Needed Packages</h2>
<p>Let’s load all the packages needed for this chapter (this assumes you’ve already installed them). If needed, read Section <a href="2-getting-started.html#packages">2.3</a> for information on how to install and load R packages.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(janitor)
<span class="kw">library</span>(moderndive)
<span class="kw">library</span>(infer)</code></pre></div>
<div id="theory" class="section level3">
<h3><span class="header-section-number">7.1.1</span> Theory based upon assumptions and models</h3>
<p>In the table below, we provide some basic properties of common sampling statistics you are likely to encounter in this course. (How do we know these properties are true? These have been proven mathematically by statisticians.)</p>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:SE-table">TABLE 7.1: </span>Properties of Sample Statistics
</caption>
<thead>
<tr>
<th style="text-align:left;">
Statistic
</th>
<th style="text-align:left;">
Population parameter
</th>
<th style="text-align:left;">
Sample statistic
</th>
<th style="text-align:left;">
Biased?
</th>
<th style="text-align:left;">
SE of sample statistic
</th>
<th style="text-align:left;">
Distribution (small n)
</th>
<th style="text-align:left;">
Distribution (large n)
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;width: 0.5in; ">
Proportion
</td>
<td style="text-align:left;width: 0.7in; ">
<span class="math inline">\(\pi\)</span>
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(\widehat{\pi}\)</span>
</td>
<td style="text-align:left;width: 1.1in; ">
Unbiased
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(\frac{\hat{\pi}(1-\hat{\pi})}{\sqrt{n}}\)</span>
</td>
<td style="text-align:left;">
Normal
</td>
<td style="text-align:left;">
Normal
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Mean
</td>
<td style="text-align:left;width: 0.7in; ">
<span class="math inline">\(\mu\)</span>
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(\overline{x}\)</span> or <span class="math inline">\(\widehat{\mu}\)</span>
</td>
<td style="text-align:left;width: 1.1in; ">
Unbiased
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(\frac{s}{\sqrt{n}}\)</span>
</td>
<td style="text-align:left;">
Normal
</td>
<td style="text-align:left;">
Normal
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Variance
</td>
<td style="text-align:left;width: 0.7in; ">
<span class="math inline">\(\sigma^2\)</span>
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(s^2\)</span>
</td>
<td style="text-align:left;width: 1.1in; ">
Unbiased
</td>
<td style="text-align:left;width: 1in; ">
?
</td>
<td style="text-align:left;">
Chi-squared
</td>
<td style="text-align:left;">
Normal
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Difference in proportions
</td>
<td style="text-align:left;width: 0.7in; ">
<span class="math inline">\(\pi_1 -\pi_2\)</span>
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(\widehat{\pi}_1 - \widehat{\pi}_2\)</span>
</td>
<td style="text-align:left;width: 1.1in; ">
Unbiased
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(\sqrt{\frac{\pi_1(1-\pi_1)}{n_1} + \frac{\pi_2(1 - \pi_2)}{n_2}}\)</span>
</td>
<td style="text-align:left;">
Normal
</td>
<td style="text-align:left;">
Normal
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Difference in means
</td>
<td style="text-align:left;width: 0.7in; ">
<span class="math inline">\(\mu_1 - \mu_2\)</span>
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(\overline{x}_1 - \overline{x}_2\)</span>
</td>
<td style="text-align:left;width: 1.1in; ">
Unbiased
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(\sqrt{\frac{s_1^2}{n_1} + \frac{s_2^2}{n_2}}\)</span>
</td>
<td style="text-align:left;">
Normal
</td>
<td style="text-align:left;">
Normal
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Regression intercept
</td>
<td style="text-align:left;width: 0.7in; ">
<span class="math inline">\(\beta_0\)</span>
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(b_0\)</span> or <span class="math inline">\(\widehat{\beta}_0\)</span>
</td>
<td style="text-align:left;width: 1.1in; ">
Unbiased
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(s^2[\frac{1}{n} + \frac{\bar{x}^2}{(n-1)s_x^2}]\)</span>
</td>
<td style="text-align:left;">
Normal
</td>
<td style="text-align:left;">
Normal
</td>
</tr>
<tr>
<td style="text-align:left;width: 0.5in; ">
Regression slope
</td>
<td style="text-align:left;width: 0.7in; ">
<span class="math inline">\(\beta_1\)</span>
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(b_1\)</span> or <span class="math inline">\(\widehat{\beta}_1\)</span>
</td>
<td style="text-align:left;width: 1.1in; ">
Unbiased
</td>
<td style="text-align:left;width: 1in; ">
<span class="math inline">\(\sqrt{\frac{s_y^2}{(n-1)s_x^2}}\)</span>
</td>
<td style="text-align:left;">
Normal
</td>
<td style="text-align:left;">
Normal
</td>
</tr>
</tbody>
</table>
<p>As an example, let’s say you are trying to estimate the population average age at the football game <span class="math inline">\(\mu\)</span>. Let’s use our simulated <code>football_fans</code> dataset again that has information on the whole population of 40,000 fans.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">76</span>)
football_fans &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">home_fan =</span> <span class="kw">rbinom</span>(<span class="dv">40000</span>, <span class="dv">1</span>, <span class="fl">0.91</span>),
                            <span class="dt">age =</span> <span class="kw">rnorm</span>(<span class="dv">40000</span>, <span class="dv">30</span>, <span class="dv">10</span>))
sample_<span class="dv">10</span> &lt;-<span class="st"> </span><span class="kw">sample_n</span>(football_fans, <span class="dt">size =</span> <span class="dv">10</span>)
<span class="kw">mean</span>(sample_<span class="dv">10</span><span class="op">$</span>age)</code></pre></div>
<pre><code>## [1] 30.8</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">var</span>(sample_<span class="dv">10</span><span class="op">$</span>age)</code></pre></div>
<pre><code>## [1] 41.3</code></pre>
<p>To estimate the average age, you take a sample of <span class="math inline">\(n = 10\)</span> participants, producing an estimate of <span class="math inline">\(\bar{x} =\)</span> 30.8 years old. Your question is simply: is this a good estimate?</p>
<ul>
<li>The estimator here is the sample mean, <span class="math inline">\(\bar{x}\)</span>.</li>
<li>We know that the sample mean provides an unbiased estimate of the population mean. In the average possible sample, this statistic will be right.</li>
<li>We know that the sampling distribution of the sample mean is the normal distribution. This is unimodal and symmetric, meaning that our estimate is just as likely larger than this population mean as it is smaller.</li>
<li>The standard error of a sample mean is <span class="math inline">\(SE(\bar{x}) = s/\sqrt{n}\)</span>. In this sample, since <span class="math inline">\(s^2 =\)</span> 41.3, we can calculate this standard error to be <span class="math inline">\(SE(\bar{x}) =\)</span> 41.3<span class="math inline">\(/\sqrt{10} =\)</span> 2.03. Comparing this to the sample mean (<span class="math inline">\(\bar{x} =\)</span> 30.8) this gives us a sense that we are somewhat close to the true parameter value.</li>
</ul>
<p>Note that we can extend the above properties to <em>differences</em> between groups as well. In general,</p>
<ul>
<li><span class="math inline">\(Bias(X_1 - X_2) = Bias(X_1) - Bias(X_2) \dashrightarrow\)</span> If <span class="math inline">\(X_1, X_2\)</span> are unbiased, then <span class="math inline">\(X_1 - X_2\)</span> is unbiased.</li>
<li><span class="math inline">\(SE(X_1 – X_2) = \sqrt{[SE(X_1)]^2 + [SE(X_2)]^2} \dashrightarrow\)</span> so long as <span class="math inline">\(X_1\)</span> and <span class="math inline">\(X_2\)</span> are independent.</li>
<li><span class="math inline">\(Dist(X_1 - X_2) \dashrightarrow\)</span> if <span class="math inline">\(X_1, X_2\)</span> are independent, then <span class="math inline">\(X_1 – X_2\)</span> are independent.</li>
</ul>
<p>This may seem really abstract. As an example, let’s focus on estimating the difference between two groups in the population <span class="math inline">\((\mu_1 - \mu_2)\)</span>. We can estimate this using <span class="math inline">\(\bar{x}_1 - \bar{x}_2\)</span>. And, using information in Table <a href="7-CIs.html#tab:SE-table">7.1</a> above, we have:</p>
<p><span class="math display">\[Bias(\bar{x}_1 - \bar{x}_2) = Bias(\bar{x}_1) - Bias(\bar{x}_2) = 0\]</span> <span class="math display">\[SE(\bar{x}_1 - \bar{x}_2) = \sqrt{[SE(\bar{x}_1)]^2 + [SE(\bar{x}_2)]^2} = \sqrt{(s_1^2/n_1 + s_2^2/n_2)}\]</span> <span class="math display">\[\bar{x}_1 - \bar{x}_2 \sim normally \ \ distributed\]</span></p>
<p>What does this mean for your data analysis?</p>
<ul>
<li>You need to think about sample size and how it might affect the sampling distribution.</li>
<li>If you have a large enough sample (e.g., <span class="math inline">\(n &gt; 50\)</span>), you can probably assume the sampling distribution is normally distributed.</li>
<li>If you have a smaller sample (e.g., <span class="math inline">\(n &lt; 50\)</span>), you should look up what the appropriate sampling distribution would be (e.g., t-distribution, F-distribution).</li>
</ul>
<p>Importantly, what this does not mean is that you need to get a larger sample!</p>
</div>
<div id="bootstrap" class="section level3">
<h3><span class="header-section-number">7.1.2</span> 10.2 Bootstrap</h3>
<p>The properties developed above are based on mathematical proofs. These proofs require assumptions and it is sometimes hard to know if the assumptions have been met. Also, the table we have provided only lists a small number of statistics. What if the parameter you are estimating requires a more complex estimator and you aren’t sure of its sampling distribution?</p>
<p>This problem provides the motivation for the <strong>bootstrap</strong>. The idea of the bootstrap is to approximate the sampling distribution of an estimator based upon the sample of data you have in front of you. The procedure is as follows:</p>
<ul>
<li>You have a sample size of <span class="math inline">\(n\)</span> (e.g., <span class="math inline">\(n = 100\)</span>)</li>
<li>Randomly select 1 observation and record its value. Return the observation to the sample. Now repeat this <span class="math inline">\(n\)</span> times. This is called <strong>sampling with replacement</strong> – note that in this procedure, the same observation may be selected multiple times, and other observations may not be selected at all.</li>
<li>For that simulated sample of size <span class="math inline">\(n\)</span>, calculate the sample statistic.</li>
<li>Repeat this process many, many, many (e.g., 10,000) times. Clearly, if you were to do this by hand this would be impossible. But this procedure can be conducted using a computer very quickly.</li>
</ul>
<p>At the end of this bootstrap procedure, you are able to see:</p>
<ul>
<li>An estimate of the sampling distribution</li>
<li>A <em>bootstrap</em> estimate of the standard error</li>
</ul>
<p>In cases in which there are also mathematical formulas available, bootstrap results should be very similar to those based off the formulas. When they are very different, however, this suggests that some of the assumptions used to develop the mathematical results might have been violated in the data.</p>
</div>
</div>
<div id="resampling-tactile" class="section level2">
<h2><span class="header-section-number">7.2</span> Pennies activity</h2>
<p>As we did in Chapter <a href="6-sampling.html#sampling">6</a>, we’ll begin with a hands-on tactile activity.</p>
<div id="what-is-the-average-year-on-us-pennies-in-2019" class="section level3">
<h3><span class="header-section-number">7.2.1</span> What is the average year on US pennies in 2019?</h3>
<p>Try to imagine all pennies being used in the United States in 2019. That’s a lot of pennies! Now say we’re are interested in the average year of minting of <em>all</em> these pennies. One way to compute this value would be to gather up all pennies being used in the US, record the year, and compute the average. This would be near impossible! So instead, let’s collect a sample of 50 pennies collected from a local bank in downtown Northampton, Massachusetts, the USA seen in Figure <a href="7-CIs.html#fig:resampling-exercise-a">7.1</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:resampling-exercise-a"></span>
<img src="images/sampling/pennies/bank.jpg" alt="Collecting a sample of 50 US pennies from a local bank." width="40%" /><img src="images/sampling/pennies/roll.jpg" alt="Collecting a sample of 50 US pennies from a local bank." width="40%" />
<p class="caption">
FIGURE 7.1: Collecting a sample of 50 US pennies from a local bank.
</p>
</div>
<p>An image of these 50 pennies can be seen in Figure <a href="7-CIs.html#fig:resampling-exercise-b">7.2</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:resampling-exercise-b"></span>
<img src="images/sampling/pennies/pennies_trim.jpg" alt="50 US pennies." width="100%" />
<p class="caption">
FIGURE 7.2: 50 US pennies.
</p>
</div>
<p>For each of the 50 pennies let’s assign an “ID” label and mark the year of minting, starting in the top left and ending in the bottom right progressing row by row, as seen in Figure <a href="7-CIs.html#fig:resampling-exercise-c">7.3</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:resampling-exercise-c"></span>
<img src="images/sampling/pennies/deliverable/3.jpg" alt="50 US pennies labelled." width="100%" />
<p class="caption">
FIGURE 7.3: 50 US pennies labelled.
</p>
</div>
<p>The <code>moderndive</code>  package contains this data on our 50 sampled pennies. Let’s explore this sample data first:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pennies_sample</code></pre></div>
<pre><code>## # A tibble: 50 x 2
##       ID  year
##    &lt;int&gt; &lt;dbl&gt;
##  1     1  2002
##  2     2  1986
##  3     3  2017
##  4     4  1988
##  5     5  2008
##  6     6  1983
##  7     7  2008
##  8     8  1996
##  9     9  2004
## 10    10  2000
## # … with 40 more rows</code></pre>
<p>The <code>pennies_sample</code> data frame has 50 rows corresponding to each penny with two variables. The first variable <code>ID</code> corresponds to the ID labels in Figure <a href="7-CIs.html#fig:resampling-exercise-c">7.3</a> whereas the second variable <code>year</code> corresponds to the year of minting saved as an integer.</p>
<p>Based on these 50 sampled pennies, what can we say about <em>all</em> US pennies in 2019? Let’s study some properties of our sample by performing an exploratory data analysis. Let’s first visualize the distribution of the year of these 50 pennies using our data visualization tools from Chapter <a href="#viz"><strong>??</strong></a>. Since <code>year</code> is a numerical variable, we use a histogram in Figure <a href="7-CIs.html#fig:pennies-sample-histogram">7.4</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(pennies_sample, <span class="kw">aes</span>(<span class="dt">x =</span> year)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">10</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:pennies-sample-histogram"></span>
<img src="ismaykimkuyper_files/figure-html/pennies-sample-histogram-1.png" alt="Distribution of year on 50 US pennies." width="\textwidth" />
<p class="caption">
FIGURE 7.4: Distribution of year on 50 US pennies.
</p>
</div>
<p>We observe a slightly left-skewed  distribution since most values fall in between the 1980s through 2010s with only a few older than 1970. What is the average year for the 50 sampled pennies? Eyeballing the histogram it appears to be around 1990. Let’s now compute this value exactly using our data wrangling tools from Chapter <a href="3-wrangling.html#wrangling">3</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pennies_sample <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_year =</span> <span class="kw">mean</span>(year))</code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   mean_year
##       &lt;dbl&gt;
## 1     1995.</code></pre>
<p>Thus assuming <code>pennies_sample</code> is a representative sample from the population of all US pennies, a “good guess” of the average year of minting of all US pennies would be 1995.44, the average year of minting of our 50 sampled pennies. This should all start sounding similar to what we did previously in Chapter <a href="6-sampling.html#sampling">6</a>!</p>
<p>In Chapter <a href="6-sampling.html#sampling">6</a> our study population was the bowl of <span class="math inline">\(N\)</span> = 2400 balls. Our population parameter of interest was the population proportion of these balls that were red, denoted mathematically by <span class="math inline">\(p\)</span>. In order to estimate <span class="math inline">\(p\)</span>, we extracted a sample of 50 balls using the shovel and computed the relevant point estimate: the sample proportion of these 50 balls that were red, denoted mathematically by <span class="math inline">\(\widehat{p}\)</span>.</p>
<p>Here our study population is <span class="math inline">\(N\)</span> = whatever the number of pennies are being used in the US, a value which we don’t know and probably never will. The population parameter of interest is now the <em>population mean</em> year of all these pennies, a value denoted mathematically by the Greek letter <span class="math inline">\(\mu\)</span> pronounced “mu”. In order to estimate <span class="math inline">\(\mu\)</span>, we went to the bank and obtained a sample of 50 pennies and computed the relevant point estimate: the <em>sample mean</em> year of these 50 pennies, denoted mathematically by <span class="math inline">\(\overline{x}\)</span> pronounced “x-bar”. An alternative and more intuitive notation for the sample mean is <span class="math inline">\(\widehat{\mu}\)</span>. However this is unfortunately not as commonly used, so in this text, we’ll always denote the sample mean as <span class="math inline">\(\overline{x}\)</span>.</p>
<p>Going back to our 50 sampled pennies in Figure <a href="7-CIs.html#fig:resampling-exercise-c">7.3</a>, the point estimate of interest is the sample mean <span class="math inline">\(\overline{x}\)</span> of 1995.44. This quantity is an estimate of the population mean year of all US pennies <span class="math inline">\(\mu\)</span>.</p>
<p>Recall that we also saw in Chapter <a href="6-sampling.html#sampling">6</a> that such estimates are prone to sampling variation. For example, in this particular sample in Figure <a href="7-CIs.html#fig:resampling-exercise-c">7.3</a>, we observed three pennies with the year of 1999. If we obtained other samples of size 50 would we always observe exactly three pennies with the year of 1999? More than likely not. We might observe none, or one, or two, or maybe even all 50! The same can be said for the other 26 unique years that are represented in our sample of 50 pennies.</p>
<p>To study this sampling variation as we did in Chapter <a href="6-sampling.html#sampling">6</a>, we need more than one sample. In our case with pennies, how would we obtain another sample? We would go to the bank and get another roll of 50 pennies! However, in real-life sampling one doesn’t obtain many samples as we did in Chapter <a href="6-sampling.html#sampling">6</a>; those were merely simulations. So what how can we study sample-to-sample variation when we have only a single sample as in our case?</p>
<p>Just as different uses of the shovel in the bowl led to the different sample proportions red, different samples of 50 pennies will lead to different sample mean years. However, how can we study the effect of sampling variation using only our <em>single sample</em> seen in Figure <a href="7-CIs.html#fig:resampling-exercise-c">7.3</a>? We will do so using a technique known as “bootstrap resampling with replacement”, which we now illustrate.</p>
</div>
<div id="resampling-once" class="section level3">
<h3><span class="header-section-number">7.2.2</span> Resampling once</h3>
<p><strong>Step 1</strong>: Let’s print out identically-sized slips of paper representing the 50 pennies in Figure <a href="7-CIs.html#fig:resampling-exercise-c">7.3</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:tactile-resampling-1"></span>
<img src="images/sampling/pennies/tactile_simulation/1_paper_slips.png" alt="50 slips of paper representing 50 US pennies." width="50%" />
<p class="caption">
FIGURE 7.5: 50 slips of paper representing 50 US pennies.
</p>
</div>
<p><strong>Step 2</strong>: Put the 50 small pieces of paper into a hat or tuque.</p>
<div class="figure" style="text-align: center"><span id="fig:tactile-resampling-2"></span>
<img src="images/sampling/pennies/tactile_simulation/2_insert_in_hat.png" alt="Putting 50 slips of paper in a hat." width="50%" />
<p class="caption">
FIGURE 7.6: Putting 50 slips of paper in a hat.
</p>
</div>
<p><strong>Step 3</strong>: Mix the hat’s contents and draw one slip of paper at random. Record the year somewhere.</p>
<div class="figure" style="text-align: center"><span id="fig:tactile-resampling-3"></span>
<img src="images/sampling/pennies/tactile_simulation/3_draw_at_random.png" alt="Drawing one slip of paper." width="50%" />
<p class="caption">
FIGURE 7.7: Drawing one slip of paper.
</p>
</div>
<p><strong>Step 4</strong>: Put the slip of paper back in the hat! In other words, replace it!</p>
<div class="figure" style="text-align: center"><span id="fig:tactile-resampling-4"></span>
<img src="images/sampling/pennies/tactile_simulation/4_put_it_back.png" alt="Replacing slip of paper." width="50%" />
<p class="caption">
FIGURE 7.8: Replacing slip of paper.
</p>
</div>
<p><strong>Step 5</strong>: Repeat Steps 3 and 4 49 more times, resulting in 50 recorded years.</p>
<p>What we just performed was a <strong>resampling</strong>  of the original sample of 50 pennies. We are not sampling 50 pennies from the population of all US pennies as we did in our trip to the bank. Instead, we are mimicking this act by “re”-sampling 50 pennies from our originally sampled 50 pennies. However, why did we replace our resampled slip of paper back into the hat in Step 4? Because if we left the slip of paper out of the hat each time we performed Step 4, we would obtain the same 50 pennies, in the end, each time! In other words, replacing the slips of paper induces variation.</p>
<p>Being more precise with our terminology, we just performed a <strong>resampling with replacement</strong> of the original sample of 50 pennies. Had we left the slip of paper out of the hat each time we performed Step 4, this would be “resampling without replacement”.</p>
<p>Let’s study our 50 resampled pennies via an exploratory data analysis. First, let’s load the data into R by manually creating a data frame <code>pennies_resample</code> of our 50 resampled values. We’ll do this using the <code>tibble()</code> command from the <code>dplyr</code> package. Note that the 50 values you obtained will almost certainly not be the same as ours.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pennies_resample &lt;-<span class="st"> </span><span class="kw">tibble</span>(
  <span class="dt">year =</span> <span class="kw">c</span>(<span class="dv">1976</span>, <span class="dv">1962</span>, <span class="dv">1976</span>, <span class="dv">1983</span>, <span class="dv">2017</span>, <span class="dv">2015</span>, <span class="dv">2015</span>, <span class="dv">1962</span>, <span class="dv">2016</span>, <span class="dv">1976</span>, 
           <span class="dv">2006</span>, <span class="dv">1997</span>, <span class="dv">1988</span>, <span class="dv">2015</span>, <span class="dv">2015</span>, <span class="dv">1988</span>, <span class="dv">2016</span>, <span class="dv">1978</span>, <span class="dv">1979</span>, <span class="dv">1997</span>, 
           <span class="dv">1974</span>, <span class="dv">2013</span>, <span class="dv">1978</span>, <span class="dv">2015</span>, <span class="dv">2008</span>, <span class="dv">1982</span>, <span class="dv">1986</span>, <span class="dv">1979</span>, <span class="dv">1981</span>, <span class="dv">2004</span>, 
           <span class="dv">2000</span>, <span class="dv">1995</span>, <span class="dv">1999</span>, <span class="dv">2006</span>, <span class="dv">1979</span>, <span class="dv">2015</span>, <span class="dv">1979</span>, <span class="dv">1998</span>, <span class="dv">1981</span>, <span class="dv">2015</span>, 
           <span class="dv">2000</span>, <span class="dv">1999</span>, <span class="dv">1988</span>, <span class="dv">2017</span>, <span class="dv">1992</span>, <span class="dv">1997</span>, <span class="dv">1990</span>, <span class="dv">1988</span>, <span class="dv">2006</span>, <span class="dv">2000</span>)
)</code></pre></div>
<p>The 50 values of <code>year</code> in <code>pennies_resample</code> represent the resample of size 50 from the original sample of 50 pennies from the bank. We display the 50 resampled pennies in Figure <a href="7-CIs.html#fig:resampling-exercise-d">7.9</a>.</p>
<div class="figure" style="text-align: center"><span id="fig:resampling-exercise-d"></span>
<img src="images/sampling/pennies/deliverable/4.jpg" alt="50 resampled US pennies labelled." width="100%" />
<p class="caption">
FIGURE 7.9: 50 resampled US pennies labelled.
</p>
</div>
<p>Let’s compare the distribution of the numerical variable <code>year</code> of our 50 resampled pennies with the distribution of the numerical variable <code>year</code> of our original sample of 50 pennies from the bank in Figure <a href="#fig:origandresample"><strong>??</strong></a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(pennies_resample, <span class="kw">aes</span>(<span class="dt">x =</span> year)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">10</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Resample of 50 pennies&quot;</span>)
<span class="kw">ggplot</span>(pennies_sample, <span class="kw">aes</span>(<span class="dt">x =</span> year)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">10</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">&quot;Original sample of 50 pennies&quot;</span>)</code></pre></div>

<pre><code>## &lt;ScaleContinuousPosition&gt;
##  Range:  
##  Limits:    0 --   15</code></pre>
<pre><code>## &lt;ScaleContinuousPosition&gt;
##  Range:  
##  Limits:    0 --   15</code></pre>
<div class="figure" style="text-align: center"><span id="fig:origandresample1"></span>
<img src="ismaykimkuyper_files/figure-html/origandresample-1.png" alt="Comparing year in the resample pennies_resample with the original sample pennies_sample." width="\textwidth" />
<p class="caption">
FIGURE 7.10: Comparing <code>year</code> in the resample <code>pennies_resample</code> with the original sample <code>pennies_sample</code>.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:origandresample2"></span>
<img src="ismaykimkuyper_files/figure-html/origandresample-2.png" alt="Comparing year in the resample pennies_resample with the original sample pennies_sample." width="\textwidth" />
<p class="caption">
FIGURE 7.11: Comparing <code>year</code> in the resample <code>pennies_resample</code> with the original sample <code>pennies_sample</code>.
</p>
</div>
<p>Observe that while the general shape of the distribution of <code>year</code> is roughly similar, they are not identical. This is due to the variation induced by replacing the slips of paper each time we pull one out and recorded the year.</p>
<p>Recall from the previous section that the sample mean of the original sample of 50 pennies from the bank was 1995.44. What about for the <code>year</code> variable in <code>pennies_resample</code>? Any guesses? Let’s have <code>dplyr</code> help us out as before:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pennies_resample <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_year =</span> <span class="kw">mean</span>(year))</code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   mean_year
##       &lt;dbl&gt;
## 1     1985.</code></pre>
<p>We obtained a different mean year of 1985.06. Again, this variation is induced by the “with replacement” from the “resampling with replacement” terminology we defined earlier.</p>
<p>What if we repeated several times this resampling exercise many times? Would we obtain the same sample mean <code>year</code> value each time? In other words, would our guess at the mean year of all pennies in the US in 2019 be exactly 1985.06 every time? Just as we did in Chapter <a href="6-sampling.html#sampling">6</a>, let’s perform this resampling activity with the help of 35 of our friends.</p>
</div>
<div id="student-resamples" class="section level3">
<h3><span class="header-section-number">7.2.3</span> Resampling 35 times</h3>
<p>Each of our 35 friends will repeat the same 5 steps above:</p>
<ol style="list-style-type: decimal">
<li>Start with 50 identically-sized slips of paper representing the 50 pennies.</li>
<li>Put the 50 small pieces of paper into a hat or tuque.</li>
<li>Mix the hat’s contents and draw one slip of paper at random. Record the year somewhere.</li>
<li>Replace the slip of paper back in the hat!</li>
<li>Repeat Steps 3 and 4 49 more times, resulting in 50 recorded years.</li>
</ol>
<p>Since we had 35 of our friends perform this task, we ended up with 35 <span class="math inline">\(\times\)</span> 50 = 1750 values. We recorded these values in a <a href="https://docs.google.com/spreadsheets/d/1y3kOsU_wDrDd5eiJbEtLeHT9L5SvpZb_TrzwFBsouk0/">shared spreadsheet</a> with 50 rows (plus a header row) and 35 columns; we display a snapshot of the first 10 rows and 5 columns in Figure <a href="7-CIs.html#fig:tactile-resampling-5">7.12</a></p>
<div class="figure" style="text-align: center"><span id="fig:tactile-resampling-5"></span>
<img src="images/sampling/pennies/tactile_simulation/5_shared_spreadsheet.png" alt="Snapshot of shared spreadsheet of resampled pennies." width="70%" />
<p class="caption">
FIGURE 7.12: Snapshot of shared spreadsheet of resampled pennies.
</p>
</div>
<p>For your convenience, we’ve taken these 35 <span class="math inline">\(\times\)</span> 50 = 1750 values and saved them in <code>virtual_resamples</code>, a “tidy” data frame included in the <code>moderndive</code> package:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pennies_resamples</code></pre></div>
<pre><code>## # A tibble: 1,750 x 3
##    replicate name   year
##        &lt;int&gt; &lt;chr&gt; &lt;dbl&gt;
##  1         1 A      1988
##  2         1 A      2002
##  3         1 A      2015
##  4         1 A      1998
##  5         1 A      1979
##  6         1 A      1971
##  7         1 A      1971
##  8         1 A      2015
##  9         1 A      1988
## 10         1 A      1979
## # … with 1,740 more rows</code></pre>
<p>What did each of our 35 friends obtain as the mean year? <code>dplyr</code> to the rescue once more! After grouping the rows by <code>name</code>, we summarize each group of rows with their mean <code>year</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">resampled_means &lt;-<span class="st"> </span>pennies_resamples <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(name) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_year =</span> <span class="kw">mean</span>(year))
resampled_means</code></pre></div>
<pre><code>## # A tibble: 35 x 2
##    name  mean_year
##    &lt;chr&gt;     &lt;dbl&gt;
##  1 A         1992.
##  2 AA        1996.
##  3 B         1996.
##  4 BB        1992.
##  5 C         1996.
##  6 CC        1996.
##  7 D         1997.
##  8 DD        1997.
##  9 E         1991.
## 10 EE        1998.
## # … with 25 more rows</code></pre>
<p>Observe that <code>resampled_means</code> has 35 rows corresponding to the 35 resample means based the 35 resamples performed by our friends. Furthermore, observe the variation in the 35 values in the variable <code>mean_year</code>. This variation exists because by “resampling with replacement”, our 35 friends obtained different resamples of 50 pennies, and thus obtained different resample mean year.</p>
<p>Since the variable <code>mean_year</code> is numerical, let’s visualize its distribution using a histogram in Figure <a href="7-CIs.html#fig:tactile-resampling-6">7.13</a>. Note that adding the argument <code>boundary = 1990</code> to <code>geom_histogram()</code> sets the binning structure of the histogram so that one of the boundaries between bins is at the year 1990 exactly.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(resampled_means, <span class="kw">aes</span>(<span class="dt">x =</span> mean_year)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">1</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">boundary =</span> <span class="dv">1990</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Resampled mean year&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:tactile-resampling-6"></span>
<img src="ismaykimkuyper_files/figure-html/tactile-resampling-6-1.png" alt="Distribution of 35 sample means from 35 resamples." width="\textwidth" />
<p class="caption">
FIGURE 7.13: Distribution of 35 sample means from 35 resamples.
</p>
</div>
<p>Observe the following about the histogram in Figure <a href="7-CIs.html#fig:tactile-resampling-6">7.13</a>:</p>
<ul>
<li>The distribution looks roughly normal.</li>
<li>We rarely observe sample mean years less than in 1992.</li>
<li>On the other side of the distribution, we rarely observe sample mean years greater than in 2000.</li>
<li>The most frequently occurring values occur between roughly 1992 and 1998.</li>
<li>The distribution of these 35 sample means based on 35 resamples is roughly centered at 1995, which is the sample mean of 1995.44 of the original sample of 50 pennies from the bank.</li>
</ul>
</div>
<div id="what-did-we-just-do" class="section level3">
<h3><span class="header-section-number">7.2.4</span> What did we just do?</h3>
<p>What we just demonstrated in this activity is the statistical procedure known as <em>bootstrap resampling with replacement</em> . We used <em>resampling</em> to mimic the sampling variation we observe from sample-to-sample as we did in Chapter <a href="6-sampling.html#sampling">6</a> on sampling, but this time using a <em>single</em> sample from the population.</p>
<p>In fact, the histogram of sample means from 35 resamples in Figure <a href="7-CIs.html#fig:tactile-resampling-6">7.13</a> is called the <em>bootstrap distribution</em>  of the sample mean and it is an approximation of the <em>sampling distribution</em> of the same mean, a concept we introduced in Chapter <a href="6-sampling.html#sampling">6</a>. In Section <a href="#ci-conclusion"><strong>??</strong></a> we’ll show you that the <em>bootstrap distribution</em> is an approximation to the <em>sampling distribution</em>. Using this bootstrap distribution, we can study the effect of sampling variation on our estimates, in particular study the typical “error” of our estimates, known as the <em>standard error</em> .</p>
<p>In Section <a href="7-CIs.html#resampling-simulation">7.3</a> we’ll mimic our tactile resampling activity virtually on the computer. We can use a computer to do the resampling many more times than our 35 friends could possibly do. This will allow us to better understand the bootstrap distribution. In Section <a href="#ci-build-up"><strong>??</strong></a> we’ll explicitly articulate our goals for this chapter: understanding resampling variation, defining the statistical concept of a <em>confidence interval</em> by building on our pennies example, and discussing the interpretation of confidence intervals.</p>
<p>Following this framework on confidence intervals, we’ll discuss the <code>dplyr</code> and <code>infer</code> package code needed to complete the process of <em>bootstrapping</em>, which is another name for this resampling approach that is most commonly found in developing confidence intervals. We’ve used one of the functions in the <code>infer</code> package already with <code>rep_sample_n()</code>, but there’s a lot more to this package than just that. We’ll introduce the tidy statistical inference framework that was the motivation for the <code>infer</code> package pipeline that will be the driving package throughout the rest of this book.</p>
<p>As we did in Chapter <a href="6-sampling.html#sampling">6</a>, we’ll tie all these ideas together with a real-life case study in Section <a href="#case-study-two-prop-ci"><strong>??</strong></a> involving data from an experiment about yawning from the US television show Mythbusters. The chapter concludes with a comparison of the sampling distribution and a bootstrap distribution using the balls data from Chapter <a href="6-sampling.html#sampling">6</a> on sampling.</p>
</div>
</div>
<div id="resampling-simulation" class="section level2">
<h2><span class="header-section-number">7.3</span> Computer simulation of resampling</h2>
<p>Let’s now mimic our tactile resampling activity virtually by using our computer.</p>
<div id="virtually-resampling-once" class="section level3">
<h3><span class="header-section-number">7.3.1</span> Virtually resampling once</h3>
<p>First, let’s perform the virtual analog of resampling once. Recall that the <code>pennies_sample</code> data frame included in the <code>moderndive</code> package contains the years of our original sample of 50 pennies from the bank. Furthermore, recall in Chapter <a href="6-sampling.html#sampling">6</a> on sampling that we used the <code>rep_sample_n()</code> function as a virtual shovel to sample balls from our virtual bowl of 2400 balls.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">virtual_shovel &lt;-<span class="st"> </span>bowl <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>)</code></pre></div>
<p>Let’s combine these two elements to virtually mimic our resampling with replacement exercise involving the slips of paper representing our 50 pennies in Figure <a href="7-CIs.html#fig:resampling-exercise-c">7.3</a>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">virtual_resample &lt;-<span class="st"> </span>pennies_sample <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>)</code></pre></div>
<p>Observe how we explicitly set the <code>replace</code> argument to <code>TRUE</code> in order to tell <code>rep_sample_n()</code> that we would like to sample pennies  <em>with</em> replacement. Had we not set <code>replace = TRUE</code>, the function would’ve assumed the default value of <code>FALSE</code>. Additionally, since we didn’t specify the number of replicates via the <code>reps</code> argument, the function assumes the default of one replicate <code>reps = 1</code>. Note also that the <code>size</code> argument is set to match the original sample size of 50 pennies. So what does <code>virtual_resample</code> look like?</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">View</span>(virtual_resample)</code></pre></div>
<p>We’ll display only the first 10 out of 50 rows of <code>virtual_resample</code>’s contents in Table <a href="#tab:virtual-shovel"><strong>??</strong></a>.</p>
<table class="table" style="font-size: 16px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:virtual-resample">TABLE 7.2: </span>First 10 resampled rows of 50 in virtual sample
</caption>
<thead>
<tr>
<th style="text-align:right;">
replicate
</th>
<th style="text-align:right;">
ID
</th>
<th style="text-align:right;">
year
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
1978
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
1962
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
1990
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
1998
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
1978
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
1995
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
42
</td>
<td style="text-align:right;">
1997
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
1992
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
2016
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
1986
</td>
</tr>
</tbody>
</table>
<p>The <code>replicate</code> variable only takes on the value of 1 corresponding to us only having <code>reps = 1</code>, the <code>ID</code> variable indexes which of the 50 pennies from <code>pennies_sample</code> was resampled, and <code>year</code> denotes the year of minting.</p>
<p>Let’s compute the mean <code>year</code> in our virtual resample of size 50 using data wrangling functions included in the <code>dplyr</code> package:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">virtual_resample <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">resample_mean =</span> <span class="kw">mean</span>(year))</code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   replicate resample_mean
##       &lt;int&gt;         &lt;dbl&gt;
## 1         1         1997.</code></pre>
<p>As when we did our tactile resampling, the resulting mean year is different than that mean year of our 50 originally sampled pennies of 1995.44.</p>
<!-- 
Chester: Not sure if needed, but those trying to follow along may be mystified if we don't include this. 
Note that tibbles will try to print as pretty as possible which may result in numbers being rounded. In this chapter, we have set the default number of values to be printed to six in tibbles with `options(pillar.sigfig = 6)`.
Albert: I'm not sure if it's worth trouble to explain that command and why tidyverse opts for 3 sigfigs.
-->
</div>
<div id="virtually-resampling-35-times" class="section level3">
<h3><span class="header-section-number">7.3.2</span> Virtually resampling 35 times</h3>
<p>Let’s now have 35 virtual friends perform our virtual resampling exercise. Using these results, we’ll be able to study the variability in the sample means from 35 resamples of size 50. Let’s first add a <code>reps = 35</code> argument to <code>rep_sample_n()</code>  to indicate we would like 35 replicates, or in other words, repeat the resampling with the replacement of 50 pennies 35 times.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">virtual_resamples &lt;-<span class="st"> </span>pennies_sample <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">reps =</span> <span class="dv">35</span>)
virtual_resamples</code></pre></div>
<pre><code>## # A tibble: 1,750 x 3
## # Groups:   replicate [35]
##    replicate    ID  year
##        &lt;int&gt; &lt;int&gt; &lt;dbl&gt;
##  1         1    35  1985
##  2         1    43  2018
##  3         1    41  1992
##  4         1     4  1988
##  5         1    27  1993
##  6         1    24  2017
##  7         1    23  1998
##  8         1    37  1962
##  9         1    18  1996
## 10         1    42  1997
## # … with 1,740 more rows</code></pre>
<p>The resulting <code>virtual_resamples</code> data frame has 35 <span class="math inline">\(\times\)</span> 50 = 1750 rows corresponding to 35 resamples of 50 pennies. What did each of our 35 virtual friends obtain as the mean year? We’ll use the same <code>dplyr</code> verbs as we did in the previous section, but computing the mean for each of our virtual friends separately by adding a <code>group_by(replicate)</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">virtual_resampled_means &lt;-<span class="st"> </span>virtual_resamples <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_year =</span> <span class="kw">mean</span>(year))
virtual_resampled_means</code></pre></div>
<pre><code>## # A tibble: 35 x 2
##    replicate mean_year
##        &lt;int&gt;     &lt;dbl&gt;
##  1         1     1991.
##  2         2     1996.
##  3         3     1996.
##  4         4     1997.
##  5         5     1995.
##  6         6     1997.
##  7         7     1996.
##  8         8     2000.
##  9         9     1995.
## 10        10     1994.
## # … with 25 more rows</code></pre>
<p>Observe that <code>virtual_resampled_means</code> has 35 rows corresponding to the 35 resampled means and that the values of <code>mean_year</code> vary. Let’s visualize the distribution of the numerical variable <code>mean_year</code> using a histogram in Figure <a href="7-CIs.html#fig:tactile-resampling-7">7.14</a>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(virtual_resampled_means, <span class="kw">aes</span>(<span class="dt">x =</span> mean_year)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_histogram</span>(<span class="dt">binwidth =</span> <span class="dv">1</span>, <span class="dt">color =</span> <span class="st">&quot;white&quot;</span>, <span class="dt">boundary =</span> <span class="dv">1990</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">&quot;Resampled mean year&quot;</span>)</code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:tactile-resampling-7"></span>
<img src="ismaykimkuyper_files/figure-html/tactile-resampling-7-1.png" alt="Distribution of 35 sample means from 35 resamples." width="\textwidth" />
<p class="caption">
FIGURE 7.14: Distribution of 35 sample means from 35 resamples.
</p>
</div>
<p>To convince ourselves that our virtual resampling indeed mimics the resampling done by our 35 friends, let’s compare the bootstrap distribution we just virtually constructed with the bootstrap distribution our 35 friends constructed via tactile resampling in the previous section.</p>
<div class="figure" style="text-align: center"><span id="fig:orig-and-resample-means1"></span>
<img src="ismaykimkuyper_files/figure-html/orig-and-resample-means-1.png" alt="Comparing distributions of means from resamples." width="\textwidth" />
<p class="caption">
FIGURE 7.15: Comparing distributions of means from resamples.
</p>
</div>
<div class="figure" style="text-align: center"><span id="fig:orig-and-resample-means2"></span>
<img src="ismaykimkuyper_files/figure-html/orig-and-resample-means-2.png" alt="Comparing distributions of means from resamples." width="\textwidth" />
<p class="caption">
FIGURE 7.16: Comparing distributions of means from resamples.
</p>
</div>
<p>Recall that in the “resampling with replacement” scenario we are illustrating here both the above histograms have a special name: the <em>bootstrap distribution of the sample mean</em>. Furthermore, they are an approximation to the <em>sampling distribution</em> of the sample mean, a concept you saw in Chapter <a href="6-sampling.html#sampling">6</a> on sampling. These distributions allow us to study the effect of sampling variation on our estimates of the true population mean, in this case the true mean year for <em>all</em> US pennies. However, unlike in Chapter <a href="6-sampling.html#sampling">6</a> where we simulated the act of taking multiple samples, something one would never do in practice, bootstrap distributions are constructed from a <em>single</em> sample, in this case the 50 original pennies from the bank.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<!--
**(LC10.1)** Ask learners to compare the distributions since we did something similar in Chapter 8 and they should be well versed on this by now.
-->
<div class="learncheck">

</div>
</div>
<div id="bootstrap-1000-replicates" class="section level3">
<h3><span class="header-section-number">7.3.3</span> Virtually resampling 1000 times</h3>
<p>Remember that one of the goals of resampling with replacement is to construct the bootstrap distribution, which is an approximation of the sampling distribution of the point estimate of interest, here the sample mean year. However, the bootstrap distribution of in Figure <a href="7-CIs.html#fig:tactile-resampling-7">7.14</a> is based only on 35 resamples and hence looks a little coarse. Let’s increase the number of resamples to 1000 to better observe the shape and the variability from one resample to the next.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># Repeat resampling 1000 times</span>
virtual_resamples &lt;-<span class="st"> </span>pennies_sample <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">reps =</span> <span class="dv">1000</span>)
<span class="co"># Compute 1000 sample means</span>
virtual_resampled_means &lt;-<span class="st"> </span>virtual_resamples <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_year =</span> <span class="kw">mean</span>(year))</code></pre></div>
<p>However, in the interest of brevity, going forward let’s combine the above two operations into a single chain of <code>%&gt;%</code> pipe operators:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">virtual_resampled_means &lt;-<span class="st"> </span>pennies_sample <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">rep_sample_n</span>(<span class="dt">size =</span> <span class="dv">50</span>, <span class="dt">replace =</span> <span class="ot">TRUE</span>, <span class="dt">reps =</span> <span class="dv">1000</span>) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">group_by</span>(replicate) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_year =</span> <span class="kw">mean</span>(year))
virtual_resampled_means</code></pre></div>
<pre><code>## # A tibble: 1,000 x 2
##    replicate mean_year
##        &lt;int&gt;     &lt;dbl&gt;
##  1         1     1993.
##  2         2     1994.
##  3         3     1993.
##  4         4     1998.
##  5         5     1997.
##  6         6     1991.
##  7         7     1999.
##  8         8     1999.
##  9         9     1995.
## 10        10     1995.
## # … with 990 more rows</code></pre>
<p>Let’s visualize the bootstrap distribution of these 1000 sample means from 1000 virtual resamples looks like in Figure <a href="7-CIs.html#fig:one-thousand-sample-means">7.17</a>:</p>
<div class="figure" style="text-align: center"><span id="fig:one-thousand-sample-means"></span>
<img src="ismaykimkuyper_files/figure-html/one-thousand-sample-means-1.png" alt="Bootstrap resampling distribution based on 1000 resamples." width="\textwidth" />
<p class="caption">
FIGURE 7.17: Bootstrap resampling distribution based on 1000 resamples.
</p>
</div>
<p>Note here the bell shape starting to become more apparent. We now have a general sense for the range of values that the sample mean may take on in these resamples from this histogram of the bootstrap distribution. Do you have a guess as to where this histogram is centered? With it being close to symmetric, either the mean or the median would serve as a good estimate for the center here. Let’s compute the mean:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">virtual_resampled_means <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">summarize</span>(<span class="dt">mean_of_means =</span> <span class="kw">mean</span>(mean_year))</code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   mean_of_means
##           &lt;dbl&gt;
## 1         1995.</code></pre>
<p>The mean of the 1000 means from 1000 resamples is 1995.461. Note that this is quite close to the mean of our original sample of 50 pennies from the bank: 1995.44. This is the case since each of the 1000 resamples are based on the original sample of 50 pennies.</p>
<div class="learncheck">
<p>
<strong><em>Learning check</em></strong>
</p>
</div>
<p><strong>(LC10.2)</strong> What is the difference between a bootstrap distribution and a sampling distribution?</p>
<!--
**(LC10.3)** Ask learners to summarize important features of the plot as was done in Chapter 8.
-->
<div class="learncheck">

</div>
</div>
<div id="combining-an-estimate-with-its-precision" class="section level3">
<h3><span class="header-section-number">7.3.4</span> 10.3 Combining an estimate with its precision</h3>
<p>A <strong>confidence interval</strong> gives a range of plausible values for a parameter. It depends on a specified confidence level with higher confidence levels corresponding to wider confidence intervals and lower confidence levels corresponding to narrower confidence intervals. Common confidence levels include 90%, 95%, and 99%.</p>
<p>Usually we don’t just begin sections with a definition, but <em>confidence intervals</em> are simple to define and play an important role in the sciences and any field that uses data. You can think of a confidence interval as playing the role of a net when fishing. Instead of just trying to catch a fish with a single spear (estimating an unknown parameter by using a single point estimate/statistic), we can use a net to try to provide a range of possible locations for the fish (use a range of possible values based around our statistic to make a plausible guess as to the location of the parameter).</p>
</div>
<div id="ci-with-the-normal-distribution" class="section level3">
<h3><span class="header-section-number">7.3.5</span> 10.4 CI with the Normal distribution</h3>
<p>If the sampling distribution of an estimator is normally distributed, then we can use properties of the standard normal distribution to create a confidence interval: * 95% of the values are between -1.96 and +1.96. * 90% of values are between -1.68 and +1.68.</p>
<p>Using this, we can define a 95% confidence interval for a population parameter as, <span class="math display">\[(Estimate – 1.96*SE(Estimate), \ Estimate + 1.96*SE(Estimate))\]</span> For example, a 95% confidence interval for the population mean <span class="math inline">\(\mu\)</span> can be constructed based upon the sample mean as, <span class="math display">\[(\bar{x} - 1.96 * SE(\bar{x}), \ \bar{x} + 1.96*SE(\bar{x}))\]</span></p>
<p>A few properties are worth keeping in mind: * This interval is <em>symmetric</em>. This symmetry falls from the fact that the normal distribution is a symmetric distribution. <em>If the sampling distribution is not normal, the confidence interval may not be symmetric</em>. * The multiplier 1.96 used in this interval corresponding to 95% comes directly from properties of the normal distribution. <em>If the sampling distribution is not normal, this multiplier might be different</em>. For example, this multiplier is <em>larger</em> when the distribution has heavy tails, as with the t-distribution.</p>
</div>
<div id="ci-via-bootstrap" class="section level3">
<h3><span class="header-section-number">7.3.6</span> 10.5 CI via Bootstrap</h3>
<p>When you are not sure what the appropriate sampling distribution is, or when you are worried that your assumptions might be wrong, confidence intervals can be created using a bootstrapping process.</p>
<p>{current 9.3, 9.3.1 sections}</p>
</div>
<div id="interpreting-a-confidence-interval" class="section level3">
<h3><span class="header-section-number">7.3.7</span> 10.6 Interpreting a Confidence Interval</h3>
<p>Like many statistics, while a confidence interval is fairly straightforward to construct, it is very easy to interpret incorrectly. In fact, many researchers – statisticians included – get the interpretation of confidence intervals wrong. This goes back to the idea of <strong>counterfactual thinking</strong> that we introduced previously: A confidence interval is a property of a population and estimator, not a particular sample. It asks: if I constructed this interval in every possible sample, in what percentage of samples would I correctly include the true population parameter?</p>
<p>To see this, let’s return to the sampling distribution of the sample mean. {hist of sampling dis here} Assume that we drew this observation (pick a point near to the mean) and constructed a 95% confidence interval. In this case, the population mean would be in this interval, right? (Yes). {now oen in the tail highlighted} Assume now that we were unlucky and got an observation far from the population mean and constructed a 95% confidence interval. In this case, is the population mean in this interval? (No). Importantly, remember that in the data we have in front of us <em>we don’t know what the population mean is</em> and we don’t know if our estimate is the value near to the mean (case 1) or far from the mean (case 2).</p>
<p>Another way to visualize this is via the intervals themselves: {Plot from current 9.5}</p>
</div>
<div id="examples-from-end-of-current-chapter-9" class="section level3">
<h3><span class="header-section-number">7.3.8</span> 10.7 Examples (from end of current chapter 9)</h3>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="6-sampling.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="8-inference-for-regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/nulib/moderndive_book/edit/master/10-confidence-intervals.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
